spring:
  application:
    name: yun-ai-code-live-backend
  # mysql 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun_ai_code_live
    username: thefang
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api

springdoc: # springdoc-openapi 项目接口文档的配置
  swagger-ui:
    path: /swagger-ui.html # Knife4j 文档访问路径
    tags-sorter: alpha # 标签排序
    operations-sorter: alpha # 接口按名称排序
  api-docs:
    path: /v3/api-docs # OpenAPI 描述文件路径
  info: # 文档接口信息描述
    title: Yun AI Code Live API  # 文档标题
    version: 1.0.0 # 文档版本
    contact: # 文档作者
      name: Thefang
      url: https://github.com/cvThefang
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.thefang.yunaicodelive.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn